### ISSUE TITLE
False posititives?

### ISSUE THREAD

**Issue by lolmaus** [steveszc/ember-cli-memory-leak-detector#32] opened 2020-12-29 07:51 UTC
Hi!

I installed the addon to a fresh app, updated the testem config and ran `ember t -s`.

It reported every userland class as retained! The number of instances for each class seems to correspond to the number of times they've been used in tests, so basically everything was retained.

I've also tried capturing a memory allocation timeline snapshot manually in `http://localhost:4200/tests` mode and it showed 0% retention for both userland classes such as `ApplicationRoute` and Ember classes such as `RouterService`. So basically the report generated by the addon is wrong.

**Comment by lolmaus** [comment] 2020-12-29 07:54
![image](https://user-images.githubusercontent.com/200884/103268175-24844d00-49c4-11eb-8f02-3a7f30f51132.png)

![image](https://user-images.githubusercontent.com/200884/103268163-1d5d3f00-49c4-11eb-9159-7588d5190acf.png)

**Comment by steveszc** [comment] 2021-01-06 00:54
Not sure what to make of this. I've run this addon against against real apps and addons and not run in to false positives of the kind you're reporting here. However, the test coverage and my manual testing have been pretty limited this far, so it's very possible things may not work quite right in certain project configurations. 

Was there anything non-standard about your project? 
Are you able to share your reproduction repo?

Also, you may try the setting the writeSnapshot option to true and uploading the resulting snapshot file into chrome devtools to double check what is retained.

**Comment by steveszc** [comment] 2021-03-31 03:41
Since this issue originally reported I've run the addon on several additional apps and addons and have not run into anything like what was reported here. I'm going to close this for now, but I'm happy to re-open if anyone else runs into this, or if a reproduction repo can be provided.

**Closed by steveszc** 2021-03-31 03:41 UTC

**Comment by steveszc** [comment] 2021-03-31 03:45
Also, unsure if this is related, but within the last month I added the additional step of running GC prior to capturing the heap snapshot. Its possible that *not* running this manual GC could have produced an incorrect result inline with what was reported here... so hopefully that was the issue and its fixed now 🤞 

https://github.com/steveszc/ember-cli-memory-leak-detector/commit/796575ba611a6583f65cf9e1fa5eedbbd49e5811
